const COLLECTION = {
  namespace: 'collections',
  getters: {
    GET_COLLECTIONS: 'GET_COLLECTIONS',
    GET_COLLECTIONS_FOR_FILTER: 'GET_COLLECTIONS_FOR_FILTER',
    GET_COLLECTIONS_TABLE_HEADER: 'GET_COLLECTIONS_TABLE_HEADER',
    GET_COLLECTION: 'GET_COLLECTION',
    GET_LOADING: 'GET_LOADING'
  },
  actions: {
    GET_COLLECTIONS: 'GET_COLLECTIONS',
    GET_COLLECTION: 'GET_COLLECTION',
    CREATE_COLLECTION: 'CREATE_COLLECTION',
    UPDATE_COLLECTION: 'UPDATE_COLLECTION',
    DELETE_COLLECTION: 'DELETE_COLLECTION'
  },
  mutations: {
    SET_COLLECTIONS: 'SET_COLLECTIONS',
    SET_COLLECTION: 'SET_COLLECTION',
    SET_COLLECTIONS_FOR_FILTER: 'SET_COLLECTIONS_FOR_FILTER',
    CREATE_COLLECTION: 'CREATE_COLLECTION',
    UPDATE_COLLECTION: 'UPDATE_COLLECTION',
    DELETE_COLLECTION: 'DELETE_COLLECTION',
    SET_COLLECTION_IMAGES: 'SET_COLLECTION_IMAGES',
    SET_LOADING: 'SET_LOADING'
  }
}

export default COLLECTION
