const DASHBOARD = {
  namespace: 'dashboard',
  getters: {
    GER_DS_SUMMARY: 'GET_DS_SUMMARY',
    GET_TRANSACTIONS_PREVIEW: 'GET_TRANSACTIONS_PREVIEW'
  },
  actions: {
    GET_DS_SUMMARY: 'GET_DS_SUMMARY',
    GET_TRANSACTIONS_PREVIEW: 'GET_TRANSACTIONS_PREVIEW'
  },
  mutations: {
    SET_DS_SUMMARY: 'SET_DS_SUMMARY',
    SET_TRANSACTIONS_PREVIEW: 'SET_TRANSACTIONS_PREVIEW'
  }
}

export default DASHBOARD
