const REMIT = {
  namespace: 'remits',
  getters: {
    GET_REMITS: 'GET_REMITS',
    GET_REMITS_TRANSACTION_PREVIEW_HEADER: 'GET_REMITS_TRANSACTION_PREVIEW_HEADER',
    GET_TABLE_HEADER: 'GET_TABLE_HEADER',
    GET_SELECTED_TRANSACTIONS: 'GET_SELECTED_TRANSACTIONS',
    GET_REMIT_DIALOG_STATUS: 'GET_REMIT_DIALOG_STATUS',
    GET_TOTAL: 'GET_TOTAL',
    GET_REMIT_TRANSACTIONS: 'GET_REMIT_TRANSACTIONS',
    GET_REMIT: 'GET_REMIT',
    GET_LOADING: 'GET_LOADING',
    DOWNLOADING_REPORT: 'DOWNLOADING_REPORT'
  },
  actions: {
    GET_REMITS: 'GET_REMITS',
    CREATE_REMIT: 'CREATE_REMIT',
    UPDATE_SELECTED_TRANSACTIONS: 'UPDATE_SELECTED_TRANSACTIONS',
    OPEN_REMIT_DIALOG: 'OPEN_REMIT_DIALOG',
    CLOSE_REMIT_DIALOG: 'CLOSE_REMIT_DIALOG',
    GET_REMIT_TRANSACTIONS: 'GET_REMIT_TRANSACTIONS',
    GET_REMIT: 'GET_REMIT',
    DOWNLOAD_REMIT_REPORT: 'DOWNLOAD_REMIT_REPORT'
  },
  mutations: {
    SET_REMITS: 'SET_REMITS',
    ADD_REMIT: 'ADD_REMIT',
    UPDATE_SELECTED_TRANSACTIONS: 'UPDATE_SELECTED_TRANSACTIONS',
    UPDATE_REMIT_DIALOG_STATUS: 'UPDATE_REMIT_DIALOG_STATUS',
    SET_REMIT_TRANSACTIONS: 'SET_REMIT_TRANSACTIONS',
    SET_REMIT: 'SET_REMIT',
    SET_LOADING: 'SET_LOADING',
    SET_DOWNLOADING_REPORT: 'SET_DOWNLOADING_REPORT'
  }
}

export default REMIT
