const TRANSACTION = {
  namespace: 'transactions',
  getters: {
    GET_FILTER: 'GET_FILTER',
    GET_TRANSACTIONS: 'GET_TRANSACTIONS',
    GET_TRANSACTIONS_TABLE_HEADER: 'GET_TRANSACTIONS_TABLE_HEADER',
    GET_STATUS_COLOR: 'GET_STATUS_COLOR',
    GET_TYPE_COLOR: 'GET_TYPE_COLOR',
    REMITTABLE: 'REMITTABLE',
    GET_LOADING: 'GET_LOADING'
  },
  actions: {
    GET_TRANSACTIONS: 'GET_TRANSACTIONS'
  },
  mutations: {
    SET_TRANSACTIONS: 'SET_TRANSACTIONS',
    SET_LOADING: 'SET_LOADING'
  }
}

export default TRANSACTION
