const UNIT = {
  namespace: 'units',
  getters: {
    GET_UNITS: 'GET_UNITS',
    GET_UNITS_FOR_FILTER: 'GET_UNITS_FOR_FILTER',
    GET_UNITS_TABLE_HEADER: 'GET_TRANSACTIONS_TABLE_HEADER',
    GET_UNIT: 'GET_UNIT'

  },
  actions: {
    GET_UNITS: 'GET_UNITS',
    GET_UNIT: 'GET_UNIT',
    CREATE_UNIT: 'CREATE_UNIT',
    UPDATE_UNIT: 'UPDATE_UNIT',
    DELETE_UNIT: 'DELETE_UNIT'
  },
  mutations: {
    SET_UNITS: 'SET_UNITS',
    SET_UNIT: 'SET_UNIT',
    SET_UNITS_FOR_FILTER: 'SET_UNITS_FOR_FILTER',
    CREATE_UNIT: 'CREATE_UNIT',
    UPDATE_UNIT: 'UPDATE_UNIT',
    DELETE_UNIT: 'DELETE_UNIT'
  }
}

export default UNIT
